### ISSUE TITLE
[All pages] wrong og:image url & description meta tag missing content should be fixed

### ISSUE THREAD

**Issue by hsuanchi** [pycontw/pycontw-2021#102]
## Description

**Describe the bug**

For the OG part, the og:image URL should be a full URL, and suggest to adding the `<meta property="og:url" content="{{same as canonical}}" />`

![image](https://user-images.githubusercontent.com/24913710/125183292-fcfe1f00-e247-11eb-8a2e-cf0e5c42febd.png)
![image](https://user-images.githubusercontent.com/24913710/125183307-2323bf00-e248-11eb-8023-65a7f14423d9.png)

The meta tag of the description is missing. Please add the content as same as og:description part.

![image](https://user-images.githubusercontent.com/24913710/125183288-e6f05e80-e247-11eb-91e8-ba0f1e18438a.png)

## Steps to Reproduce

1. go to this [webstioe](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Ftw.pycon.org%2F2021%2Fen-us), can check for the Facebook og part.

**Comment by mattwang44** [comment]
closed by #112
