### ISSUE TITLE
[Keynote] keynote style改動

### ISSUE THREAD

**Issue by anan0202** [pycontw/pycontw-2021#128]
## Description
1.講者姓名、演講主題、tag名稱（講者、演講）字體大小為２０
2.講者姓名、演講主題、tag名稱（講者、演講）字重為Black （其他頁面也一起做更動）
![image](https://user-images.githubusercontent.com/86242317/127861074-1e5dbcf8-c6b7-4247-9118-08a05576ea21.png)

## Steps to Reproduce

1. Go to index
2. Click on keynote
3. See error

## Expected Behavior
1.講者姓名、演講主題、tag名稱（講者、演講）字體大小為２０
2.講者姓名、演講主題、tag名稱（講者、演講）字重為Black
![image](https://user-images.githubusercontent.com/86242317/127861357-52292240-dcab-4e2e-9954-7bff47ab9891.png)

**Comment by mattwang44** [comment]
closed by #140
