### ISSUE TITLE
[YouTube subscription] url does not work

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycontw-2021#130]
## Description
The url used for youtube subscription in the landing page does not work anymore.

## Steps to Reproduce
1. Go to the landing page
2. Click on YouTube --> subscribe

## Expected Behavior
Users are redirected to youtube and being subscribed automatically

## Actual Behavior
Users are redirected to youtube and youtube complains `This page isn't available. Sorry about that. Try searching for something else.`

## Additional context
We may want to use this permanent url instead https://www.youtube.com/channel/UCHLnNgRnfGYDzPCCH8qGbQw

**Comment by mattwang44** [comment]
The currently-used URLs are replaced with the permanent one in #129.

**Comment by mattwang44** [comment]
I believe it's fine to use the URL provided in this issue. Welcome to open another issue/PR if there is any better choice.
