### ISSUE TITLE
[Feature Request] create logo alt to associate each sponsor

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycontw-2021#160]
## Describe the solution you'd like
in short, the current GTM only catches events but not associate them with sponsorship logo alt. The click numbers of each logo is important in the post-event report for sponsors.

## Describe alternatives you've considered
Add alt s for each sponsor logo

## Additional context
context from private discord https://discord.com/channels/752904426057892052/884254959397376011/884355555014086667

**Comment by tai271828** [comment]
1. I checked the frontend source and saw the alt attributes of each sponsor logo
2. I randomly clicked some logos but GA does not show the numbers https://analytics.google.com/analytics/web/#/report/content-event-overview/a28961467w54938099p55919265/overview-dimensionSummary.selectedGroup=visitors&overview-dimensionSummary.selectedDimension=analytics.eventLabel/


Maybe GA needs some time to process the data? I/We will/should revisit the result later on a.k.a. please do not close this issue (yet!)

**Comment by mattwang44** [comment]
@tai271828 I do not have permission to access the link. If it's not troublesome to grant me the permission, here is my email: `mattwang44@gmail.com`.

**Comment by tai271828** [comment]
> 1. I checked the frontend source and saw the alt attributes of each sponsor logo
> 2. I randomly clicked some logos but GA does not show the numbers https://analytics.google.com/analytics/web/#/report/content-event-overview/a28961467w54938099p55919265/overview-dimensionSummary.selectedGroup=visitors&overview-dimensionSummary.selectedDimension=analytics.eventLabel/

I saw the data!!

> 
> Maybe GA needs some time to process the data? I/We will/should revisit the result later on a.k.a. please do not close this issue (yet!)

**Comment by tai271828** [comment]
> @tai271828 I do not have permission to access the link. If it's not troublesome to grant me the permission, here is my email: `mattwang44@gmail.com`.

Done. Let me know if you still have problems when reading the page. Thanks for improving/adding the feature!
