### ISSUE TITLE
[Feature Request] Embedded HackMD note on pages for keynotes and talks

### ISSUE THREAD

**Issue by mattwang44** [pycontw/pycontw-2021#177]
# [Feature Request] Embedded HackMD note on pages for keynotes and talks

## WHY

For each speech we create a HackMD shared doc for attendees. However, there is no way to access them from our official website.

## How

Store HackMD URL of each talk in the database and and serve these data for the frontend with backend API.

Preview:

![image](https://user-images.githubusercontent.com/24987826/135343179-6e231edf-469f-4241-b51e-863e8c6544ae.png)

## Potential Issues

1. 4 tab headers will be break into two lines on mobile view. 
![image](https://user-images.githubusercontent.com/24987826/135344202-d4836e9f-fcf0-4d41-87bc-dae938f5da03.png)
  - Possible solution is [scrollable tab headers](https://ej2.syncfusion.com/vue/documentation/tab/adaptive/) but the implementation could be hard.
  - Another solution is simply replacing the tab titles with shorter words. It could mitigate the issue for most devices but not those mobiles with width < 375px (e.g. iPhone 5/SE).
  ![image](https://user-images.githubusercontent.com/24987826/135346159-a0525a6d-561e-4fa2-a2d4-baeaf23b3093.png)

2. Users cannot edit on the embedded HackMD. I don't know the reason but probably HackMD just do not support it.
3. [UX issue (?)] Slido is embedded in each HackMD note and also each speech page on the website. The later one is probably redundant.

## Additional context

Discord discussion: [link](https://discord.com/channels/752904426057892052/833357942027452486/892636093965549608)
Related issue: https://github.com/pycontw/pycon.tw/issues/456

**Comment by tai271828** [comment]
Incredible!! Hey buddy you should have slept earlier and more!!

**Comment by mattwang44** [comment]
closed by #180 
also see https://github.com/pycontw/pycon.tw/pull/1045
