### ISSUE TITLE
[Index] 贊助商 light box 顏色錯誤 以及 間距須加大

### ISSUE THREAD

**Issue by anan0202** [pycontw/pycontw-2021#71]
## Description
1. 贊助商 lightbox 的 stroke 以及 標題（如圖上的‘’關於‘’） 顏色為 ''#F3CC39''
2. logo、標題、內文 以及按鈕之間需要加上 padding 
3. 贊助商公司名字下的底線可以刪除，因公司名稱太長會導致手機版本爆版
![image](https://user-images.githubusercontent.com/86242317/122784452-0fd6a100-d2e5-11eb-970a-754178cd71f3.png)
![image](https://user-images.githubusercontent.com/86242317/122786114-8b851d80-d2e6-11eb-91a6-9b8eed7e8887.png)

## Steps to Reproduce

1. Go to Index
2. Scroll down to 贊助商
4. See an error

## Expected Behavior
1. 贊助商 lightbox 的 stroke 以及 標題（如圖上的‘’關於‘’） 顏色為 ''#F3CC39''
2. logo與標題距離38px、標題與內文距離18px 、內文與按鈕距離51px 可以微調
3. 贊助商公司名字下的底線刪除
![image](https://user-images.githubusercontent.com/86242317/122785953-609ac980-d2e6-11eb-86e1-d572ee031d27.png)

## Actual Behavior
1. 贊助商 lightbox 的 stroke 以及 標題（如圖上的‘’關於‘’） 顏色為 ''#F3CC39''
2. logo、標題、內文 以及按鈕之間需要加上 padding 
3. 贊助商公司名字下的底線可以刪除，因公司名稱太長會導致手機版本爆版
![image](https://user-images.githubusercontent.com/86242317/122784452-0fd6a100-d2e5-11eb-970a-754178cd71f3.png)
![image](https://user-images.githubusercontent.com/86242317/122786114-8b851d80-d2e6-11eb-91a6-9b8eed7e8887.png)
## More Information

可以在 Figma 上看到原始設計稿首頁中的零件區進一步看
![image](https://user-images.githubusercontent.com/86242317/122788450-ed468700-d2e8-11eb-8217-3d642572a209.png)

figma連結：https://www.figma.com/file/1za4uYNpSonvgxdcLoHAzs/PyCon-Taiwan-2021-Web?node-id=166%3A0

**Comment by mattwang44** [comment]
closed by #93
