### ISSUE TITLE
[About] Wrong text and title

### ISSUE THREAD

**Issue by anan0202** [pycontw/pycontw-2021#77]
## Description
1. About 頁面中的年會歷史：「南遷」前面多一隔空格
2. 標題應為Bold 且 字體為 ‘’Noto Serif TC‘’
![image](https://user-images.githubusercontent.com/86242317/123131049-e8680b80-d47f-11eb-8dfd-80bad5758582.png)
3.  About 頁面中的pycon taiwan：關於 pycon taiwan 刪掉 pycon taiwan
![image](https://user-images.githubusercontent.com/86242317/123131098-f453cd80-d47f-11eb-88c6-4b2265c14508.png)

## Steps to Reproduce

1. Go to index
2. Click on about 的 年會歷史 跟 pycon taiwan
3. Scroll down to 南遷
4. See an error

## Expected Behavior
1.「南遷」前面多一隔空格
2. 標題應為Bold 且 字體為 ‘’Noto Serif TC‘’
![image](https://user-images.githubusercontent.com/86242317/123132083-e9e60380-d480-11eb-9b99-c96481725a5d.png)
3.  關於 pycon taiwan 刪掉 pycon taiwan
![image](https://user-images.githubusercontent.com/86242317/123132336-38939d80-d481-11eb-8625-d695978a735f.png)

**Screenshots**

## Actual Behavior

1.「南遷」前面多一隔空格
2. 標題應為Bold 且 字體為 ‘’Noto Serif TC‘’
![image](https://user-images.githubusercontent.com/86242317/123131049-e8680b80-d47f-11eb-8dfd-80bad5758582.png)
3.  關於 pycon taiwan 刪掉 pycon taiwan
![image](https://user-images.githubusercontent.com/86242317/123131098-f453cd80-d47f-11eb-88c6-4b2265c14508.png)
## More Information

可以觀看figma https://www.figma.com/file/1za4uYNpSonvgxdcLoHAzs/PyCon-Taiwan-2021-Web?node-id=166%3A0

**Comment by mattwang44** [comment]
closed by #96
