### ISSUE TITLE
[Hero image] Hero Image should update the bg-image, font-family and border

### ISSUE THREAD

**Issue by anan0202** [pycontw/pycontw-2021#84]
## Description
1. 封面的圖有更新
2. pycon taiwan 10th anniversary 的字體錯誤
3.  with pythonistas as us 那裡字體錯誤
4. 日期外圍的圈圈 stroke 為 3
![image](https://user-images.githubusercontent.com/86242317/123818184-58b4d800-d92b-11eb-80f5-51220b40a9e5.png)

## Steps to Reproduce

1. Go to index
2. See error

## Expected Behavior
1. 封面的圖有更新 可以至figma上export圖片
2. pycon taiwan 10th anniversary 的字體錯誤 可以直接從figma上export圖片
3.  with pythonistas as us 那裡字體錯誤 可以直接從figma上export圖片
4. 日期外圍的圈圈 stroke 為 3

![image](https://user-images.githubusercontent.com/86242317/123818276-6d916b80-d92b-11eb-9e8a-deabb1ffebee.png)
## Actual Behavior

1. 封面的圖有更新
2. pycon taiwan 10th anniversary 的字體錯誤
3.  with pythonistas as us 那裡字體錯誤
4. 日期外圍的圈圈 stroke 為 3
![image](https://user-images.githubusercontent.com/86242317/123818184-58b4d800-d92b-11eb-80f5-51220b40a9e5.png)

## More Information

https://www.figma.com/file/1za4uYNpSonvgxdcLoHAzs/PyCon-Taiwan-2021-Web?node-id=166%3A0

**Comment by mattwang44** [comment]
Assign to @flynnhou since it's related to #70

**Comment by mattwang44** [comment]
closed by #96
